### ISSUE TITLE
Unit test failures: "if cached_x.grad_fn.next_functions[1][0].variable is not x: IndexError: tuple index out of range"

### ISSUE THREAD

**Issue by jithunnair-amd** [ROCmSoftwarePlatform/apex#62]
The failing unit tests introduced by PyTorch commits related to "if cached_x.grad_fn.next_functions[1][0].variable is not x: IndexError: tuple index out of range" also observed on CUDA (upstream). 

test_conv2d_is_half (test_basic_casts.TestBasicCastsHalf)
test_linear_is_half (test_basic_casts.TestBasicCastsHalf)
test_whitelist_module_fp32_weight (test_cache.TestCache)
test_restoring (test_checkpointing.TestCheckpointing)
test_state_dict (test_checkpointing.TestCheckpointing)
test_gru_cell_is_half (test_rnn.TestRnnCells)
test_lstm_cell_is_half (test_rnn.TestRnnCells)
test_rnn_cell_is_half (test_rnn.TestRnnCells)

**Comment by hubertlu-tw** [comment]
A PyTorch commit introduced the above failing unit tests sometime in between rocm/pytorch:rocm4.3.1_ubuntu18.04_py3.6_pytorch_1.9.0 and 2021-10-15.

**Comment by zstreet87** [comment]
This is fixed in an open PR in upstream
https://github.com/NVIDIA/apex/pull/1282

It was mentioned that there is a hot-fix that maybe better
https://github.com/NVIDIA/apex/pull/1282j

**Comment by hubertlu-tw** [comment]
This issue is fixed by https://github.com/ROCmSoftwarePlatform/apex/pull/90.
